### ISSUE TITLE
[Legal] Activation compte, checkbox RGPD peu visible

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives-flask2#134]
A l'activation de mon compte, lorsque je clique sur le lien dans le mail reçu, si j'utilise un téléphone mobile, la checkbox n'est quasi pas visible.

On arrive quand même à cocher la case, mais cela pourrait vite devenir contraignant pour certaines personnes et générer pas mal de problèmes "je n'arrive pas à cocher"

**Comment by jnguiot** [comment]
A noter que "cliquer" sur le texte coche la case.

**Comment by fberu** [comment]
Le problème est qu'on ne voit pas la case
![image](https://user-images.githubusercontent.com/59260805/76566730-a8a92a80-64ad-11ea-950e-f2709d81371d.png)

**Comment by gdaviet** [comment]
Pour info j'ai eu le même problème sur un navigateur desktop, pas seulement mobile

**Comment by fberu** [comment]
effectivement, on vient de me le confirmer
