### ISSUE TITLE
Le mail d'activation des compte tombe dans les spams, voire est supprimé

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives-flask2#135]
Constaté sur https://test.collectives.cafannecy.fr, mais pas depuis https://collectives2.cafannecy.fr.

Le mail d'activation des comptes tombe systématiquement dans les spams, voire est supprimé.
Ce problème n'est pas constaté pour les mails annonçant la création d'une sortie.
Problème dû au lien d'activation ?

Constaté chez:
- OVH: mail taggué comme [SPAM]
- orange: mail supprimé
- gmail: mail supprimé

**Comment by jnguiot** [comment]
Etonnant, sur gmail, je reçois bien le mail.
Est-ce que tu peux me renvoyer le code source du mail?

**Comment by romaind8r** [comment]
Vous pouvez sinon créer un compte avec une adresse générée par https://www.mail-tester.com/ <https://www.mail-tester.com/> et voir le rapport.

Par contre faudrait forcer la création de compte avec une adresse autre que celle présente dans la base.





Best Regards,


Romain Desbrest 
rdesbrest@kiwize.com <mailto:rdesbrest@kiwize.com> 

Kiwize Conseil

+41 77 920 35 04

+33 650 17 45 47

**Comment by jnguiot** [comment]
J'ai fait un test:
https://www.mail-tester.com/test-4xqctgdie&reloaded=2
A voir que le mail d'origine est bloqué directement au niveau d'OVH. 
Cependant, à noter les deux WARNINGS:
- -1.396 | MISSING_DATE | Missing Date: header
- -0.14 | MISSING_MID | Missing Message-Id: header
Je vais essayer de les résoudre

**Comment by jnguiot** [comment]
Le problème est toujours présent.

**Comment by jnguiot** [comment]
RAS, en fait, ca marche
