### ISSUE TITLE
Perte de l'activité lors de l'édition et duplication d'une sortie

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives-flask2#136]
Lors de la duplication d'une sortie, tous les champs sont bien préremplis correctement SAUF l'activité. Il faudrait que le champ activité soit prérempli avec l'activité de la collective que l'on souhaite dupliquer.
Idem lors de l'édition.
A noter que je suis admin, donc que j'ai accès à toutes les activités

**Comment by jnguiot** [comment]
En effet, je reproduit le comportement.
