### ISSUE TITLE
Liste des collectives: aucune activité affichée sans une 1ère action sur le filtre

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives-flask2#139]
Suite de #92 ?

Lorsqu'on affiche la toute 1ère fois la liste des collectives, aucune ne s'affiche:
- que ce soit des collectives existantes
- ou une collective que l'on vient de créer

Des F5 sur la page ne change rien. Il faut agir sur le filtre, ie cocher puis décocher "passées" pour voir les collectives apparaître. Ensuite le problème ne se reproduit pas.

Constaté par 2 utilisateurs différents sur https://collectives2.cafannecy.fr

**Comment by jnguiot** [comment]
C'est vraiment bizarre. Je ne reproduit pas ce comportement. Ils utilisent quel navigateur?
Cependant, je pense que c'est lié à la persistence des filtres et des tris #85. 
Vu les problèmes que ca pose, je vais désactiver ce que j'ai fait dans le #85 et je remet la carte à todo

**Comment by jnguiot** [comment]
Résolu par #140
