### ISSUE TITLE
Liste des collectives: titre tronqué

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives-flask2#141]
Dans la liste des collectives, mettre le titre sur plusieurs lignes. Un titre trop long est tronqué.

![image](https://user-images.githubusercontent.com/59260805/76554023-68d64900-6495-11ea-9261-7739ee4a6785.png)

**Comment by jnguiot** [comment]
Idem, trop de slots est tronqué: 
![Screenshot_2020-03-12 Collectives Liste](https://user-images.githubusercontent.com/45011516/76554579-6a544100-6496-11ea-82e2-a27c77f6e4c3.png)
