### ISSUE TITLE
[Legal] L'acceptation de la charte RGPD entraîne l'acceptation des mentions légales

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives-flask2#161]
Un adhérent crée puis active son compte via le mail.
L'admin lui donne les droits d'encadrant.

Cet adhérent (qui est maintenant encadrant) se connecte pour la 1ère fois. Il lui est demandé d'accepté la charte RGPD. Il l'accepte.

1. A aucun moment il lui est demandé d'accepter les mentions légales et le traitement de ses données
2. L'acceptation de la charte RGPD a entraîné l'acceptation des mentions légales

L'acceptation / signature des mentions légales et de la charte RGPD doivent être décorrelés.

**Comment by jnguiot** [comment]
L'activation de son compte par le mail n'est possible que s'il accepte les mentions légales.
Peux-tu lui demander les heures de signatures du RGPD (https://collectives2.cafannecy.fr/profile/user/confidentiality) et des mentions légales (https://collectives2.cafannecy.fr/legal). Il s'agit surement de deux heures différentes, donc de deux signatures différents.

**Comment by fberu** [comment]
mea culpa! (je devais avoir la tête en vrac ce jour là :( )
