### ISSUE TITLE
Do not update end date if not matching start date

### ISSUE THREAD

**Issue by gdaviet** [Club-Alpin-Annecy/collectives-flask2#28]
Il suffirait de faire une variable qui passe à true si la date de fin a été modifiée. Cependant, AMHA, le mieux est de désactiver cette copie automatique si la date de début et de fin était différente avant le changement.

_Originally posted by @jnguiot in https://github.com/Club-Alpin-Annecy/collectives-flask2/pull/26_

**Comment by shaiton** [comment]
hum je viens de pousser une modification mineure. Répond-elle au problème ?
-> copier uniquement la date de début dans la date de fin si la date de fin n'est pas déjà définie.

**Comment by gdaviet** [comment]
Parfait, je résout le bug
