### ISSUE TITLE
Impossible to modify its own user

### ISSUE THREAD

**Issue by jnguiot** [Club-Alpin-Annecy/collectives-flask2#35]
Sine [PR34](https://github.com/Club-Alpin-Annecy/collectives-flask2/pull/34), a user cannot modify its own information (URL : /user).

When clicking on "Enregistrer", no error is displayed, but after refreshing the page, the data is back to its original value.

**Comment by gdaviet** [comment]
Ok, ca devrait être corrigé maintenant

**Comment by jnguiot** [comment]
Super, merci
