### ISSUE TITLE
Dates for internet subscription are mandatory whereas there is no place opened

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives-flask2#52]
When user sets 0 as value for internet subscription, user must set opening and closing dates*
![image](https://user-images.githubusercontent.com/59260805/71839162-d68f7e80-30ba-11ea-9100-1c4baa12e0ca.png)

**Comment by shaiton** [comment]
Bon j'ai un premier jet mais il faut que j'ajoute les tests de non reg.

**Comment by fberu** [comment]
Tout bon pour moi
