### ISSUE TITLE
Apply style to inserted XLS rows

### ISSUE THREAD

**Issue by gdaviet** [Club-Alpin-Annecy/collectives-flask2#53]
Oui, pour l'instant je n'applique pas du tout de style, donc ca utilise ceux du xlsx de départ. La lib python permet de faire ca je pense, mais ca sera pour une seconde review

_Originally posted by @gdaviet in https://github.com/Club-Alpin-Annecy/collectives-flask2/pull/48_

**Comment by shaiton** [comment]
l'export est fait en html maintenant (aussi dispo en xlsx ?)
Du coup ce problème est-il toujours valide ?

Aussi, vu le dans cette « issue » on dirait plus une demande de fonctionnalité (donc Trello) plutôt qu'une description d'anomalie. Peut-on fermer ou doit-on traiter cette « feature » ?

**Comment by gdaviet** [comment]
Oui finalement l'export html a été validé, on peut fermer le ticket
