### ISSUE TITLE
CSV import does not import the first row

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives-flask2#54]
When importing events through CSV import, the first event (eg the 2nd line of CSV file) is not taken into account

**Comment by jnguiot** [comment]
Probablement lié à cette ligne: je vais corriger le bug
https://github.com/Club-Alpin-Annecy/collectives-flask2/blob/12d15db229058bced6afea7c5bcd3eafb7293b55/collectives/event.py#L334
