### ISSUE TITLE
CSV import: bad encoding and new line not taken into account

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives-flask2#55]
When importing a text like

> /!\ Seules les personnes inscrites aux séances de PPG 2019/2020 peuvent s'inscrire.
> 
> PPG à dominante cardio (le coeur monte dans les tours, le goût du sang monte dans la bouche)
> 
> Les séances se déroulent chemin de l'Abbaye, sous la mairie d'Annecy le Vieux, de 18h30 à 19h30 (https://goo.gl/maps/qbdTctLbHis)
> 
> Affaires chaudes mais pas trop: il fait frais mais le moteur va chauffer :P

Result is
> /!\ Seules les personnes inscrites aux sÃ©ances de PPG 2019/2020 peuvent s'inscrire. PPG Ã  dominante cardio (le coeur monte dans les tours, le goÃ»t du sang monte dans la bouche) Les sÃ©ances se dÃ©roulent chemin de l'Abbaye, sous la mairie d'Annecy le Vieux, de 18h30 Ã  19h30 (https://goo.gl/maps/qbdTctLbHis) Affaires chaudes mais pas trop: il fait frais mais le moteur va chauffer :P

Note: the new lines are well taken into account when we edit the event

**Comment by jnguiot** [comment]
Les fichiers sont encodés en ISO-8859-1. Je vais les convertir en utf8 avant de les utiliser

**Comment by jnguiot** [comment]
Après test, ce comportement ne se reproduit pas sous Windows.

**Comment by jnguiot** [comment]
Je ne reproduit pas le bug sur demo.jnguiot.fr non plus. 
En réalité, je reproduit le problème quand le fichier a été encodé en UTF8 (ie modifié par quelqu'un sous Windows). Je vais rajouter un moyen de tester d'encoder en utf8, et si ca échoue ca testera l'iso-5589-1

**Comment by fberu** [comment]
> En réalité, je reproduit le problème quand le fichier a été encodé en UTF8 (ie modifié par quelqu'un sous Windows). Je vais rajouter un moyen de tester d'encoder en utf8, et si ca échoue ca testera l'iso-5589-1

alors non monsieur, je ne travaille pas sous Windows! :P 

ça fonctionne nickel maintenant.
Par contre les retours chariots ne sont pas pris en compte. Il faut éditer la collective pour que ce le soit

**Comment by jnguiot** [comment]
Ok.
@gdaviet est en train de préparer une PR sur le formatage de la description: Je crois que ça prends en compte le problème des retours chariot.
