### ISSUE TITLE
"Licence de catégorie None" on user profile

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives-flask2#61]
On user profile,
Displayed text is
![image](https://user-images.githubusercontent.com/59260805/71976416-8e856e80-3216-11ea-9f85-f0d5ef2a0edf.png)

Caterogie is not well displayed

**Comment by shaiton** [comment]
En fait vu le code on autorise les catégories vide, peut-être que tu as un type de license sans catégorie.

**Comment by fberu** [comment]
Vu avec Noé, c'est parce que j'ai activé mon compte avant que la catégorie soit géré.
Suite à la possibilité de dorénavant resynchroniser les données, c'est tout bon :)
