### ISSUE TITLE
Limit licence id to 12 digits when activating my account

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives-flask2#67]
In the "Activer mon compte" page, limit the licence id to 12 digits.
Today, there is no limit

**Comment by shaiton** [comment]
Invalid?

From the source code the test is already written.
After a simple test I can't reproduce:

    Erreur: Numéro de licence: Le numéro de licence doit contenir 12 chiffres et commecer par '7400'

**Comment by fberu** [comment]
It is when writing the licence id:
![image](https://user-images.githubusercontent.com/59260805/72340208-0c8abf00-36c8-11ea-8e85-2dd0f50efec0.png)
The check is well done

**Comment by shaiton** [comment]
Bon on peut parler français aussi puisque ce site n'a que des contributeurs francophones.
Tu demandes donc d'interdire avant de soumettre le formulaire ?
C'est possible mais ça apporte une lourdeure inutile non ?
Tant que le formulaire est refusé et qu'on préremplis les champs...

**Comment by fberu** [comment]
ah bah j'ai vu que des tickets étaient saisis en anglais, donc :)
Ok pour la lourdeur, je ferme
