### ISSUE TITLE
In French, "Synchroniser" is with a s, not a z

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives-flask2#68]
In user profile page,
"Resynchronizer mes informations FFCAM" should be "Resynchroni**s**er mes informations FFCAM"
and
"Si après synchronization ces informations ne sont toujours pas à jour" should be "Si après synchroni**s**ation ces informations ne sont toujours pas à jour"

**Comment by shaiton** [comment]
je viens d'intégrer un correctif
