### ISSUE TITLE
Afficher les collectives du jour jusqu'à l'heure de fin

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives-flask2#92]
Les collectives du jour sont en théorie afficher sur la liste jusqu'à son heure de fin. Si la collective finit à 18h elle n'est plus affichée après 18h.

Or avec une collective créée ce jour 4 février, début à minuit, fin à 23h; à 20h elle ne s'affiche pas.
https://demo.jnguiot.fr/event/101

**Comment by jnguiot** [comment]
Hum... Je la vois pourtant... Tu n'as pas un filtrage spécial?
![Screenshot_2020-02-04 Collectives Liste](https://user-images.githubusercontent.com/45011516/73778673-dbb01e00-478b-11ea-866a-49d781f846ab.png)

**Comment by jnguiot** [comment]
BTW, Je veux bien une capture d'écran de ta liste de collectives

**Comment by fberu** [comment]
Je n'avais pas de filtrage spécial mais j'ai effectivement dû jouer avec les filtre pour la voir apparaître.
Pour reproduire (scénario reproduit qu'une seule fois)
1. créer la collective du jour à une heure de fin postérieure à l'heure actuelle
2. afficher la liste des collectives: on ne la voit pas
3. cocher "passées" pour afficher les collectives passées: on la voit
4. décocher "passées": on la voit toujours

**Comment by fberu** [comment]
Je viens plus ou moins de reproduire.
Sur https://test.collectives.cafannecy.fr, je me suis connecté, il n'y avait aucune collective au programme (2 étaient passées).
J'en ai créé une, impossible de la voir dans la liste des collectives. J'ai joué avec les filtres annulées, passées, par activité, rien. Je suis allé dans mon profil, j'ai pu retrouver la collective. J'ai fait des tests dessus (ajout d'inscrits, refus, etc.) et en retournant sur la liste des collectives (accueil), elle est apparue.
Puis impossible à reproduire :(
* j'ai créé une 2ème collective, elle est bien apparue
* j'ai supprimé les 2 collectives, puis créé une nouvelle, elle est bien apparue

Nous sommes le 4 mars, et la 1ère collective qui "ne s'est pas affichée tout de suite", commençait le samedi 7 mars à 18h et se terminait le dimanche 8 mars à minui

**Comment by jnguiot** [comment]
Je pense que la persistence des filters dans tabulator est trop complexe: je les remplacerait, ca devrait résoudre le problème.

**Comment by jnguiot** [comment]
J'ai repéré une incohérence qui a dû être à la source des problèmes: le bug sera a rouvrir si on voit que ce n'est pas ça.
