### ISSUE TITLE
Problème d'affichage avec une collective du 25 janvier

### ISSUE THREAD

**Issue by fberu** [Club-Alpin-Annecy/collectives-flask2#94]
Une collective du 25 janvier semble poser un problème d'affichage sur la liste des collectives: impossible de voir les collectives de ce jour et les suivantes, sauf à fermer le panel.
Problème dans le nom ?

![image](https://user-images.githubusercontent.com/59260805/73778961-4bbea400-478c-11ea-98f3-26503ce2c3b5.png)

Une fois le panel fermé, on voit bien les collectives suivantes
![image](https://user-images.githubusercontent.com/59260805/73779043-67c24580-478c-11ea-9f77-2a364a287144.png)

A noter que ceci engendrerait un autre problème ? Les 2 collectives du 26 janvier, bien que le même jour, apparaissent dans 2 panels différents

**Comment by jnguiot** [comment]
En effet, j'ai une erreur "RangeError: invalid array length   [eventlist.js:152:13](https://github.com/Club-Alpin-Annecy/collectives-flask2/blob/63ee91fafe7080b519b1a5604d8ec3a93d6d84bb/collectives/static/js/event/eventlist.js#L152)"

**Comment by jnguiot** [comment]
De ce que je vois: il y a plusieurs collectives qui ont un nombre de slots incorrects:
```
28|Intermittents Trail|2020-01-31 19:00:00.000000|-2|0
85|annulation|2020-01-28 07:50:00.000000|-5|0
```
La sortie qui fait planté est la https://demo.jnguiot.fr/event/78 . C'est parce qu'il y a plus de partiticipants que de slots, ce qui génère un nombre négatif
Il faut donc:
- Protéger la fonction js `slots(nb, css)` en cas de nb qui n'est pas un entier naturel
- Protéger la construction de la case d'une collective dans tabulator pour qu'un exception ne fasse planter que la case
- Augmenter le nombre de slots des collectives qui ont plus de participants que de slots
- Vérifier qu'on ne peut pas dépasser le nombre de slots en rajoutant un participant "à la main"
- En lever les sorties qui ont des nombres de slots négatifs

**Comment by jnguiot** [comment]
Les sorties avec des slots négatifs ont été enlevés en réinitialisant la db en passant sur le nouveau site de test
